### ISSUE TITLE
Реализовать возможность создания брони

### ISSUE THREAD

**Issue by sabinaIsm** [Java-Java-Bootcamp/booking#19]
Пользователь вводит команду "бронь". Далее выводятся кнопки с наименование_заведения + интервал времени, например "Сказка 10 апреля 15-18" в чате бота.
Бот перепроверяет доступность указанного слота. Если слот доступен, он блокируется, иначе - бот выводит сообщение о недоступности выбранного варианта

**Comment by slovpunk** [comment]
Сегодня с Катей и ребятами обсуждали следующий вариант.
При вводе команды бронь появляются кнопки с названиями заведений, выбрав заведение, появляются кнопки со слотами, которые отражают все доступные временнЫе интервалы. Выбрав интервал, человек автоматически бронирует столик.

**Comment by AVPGenium** [comment]
![реализация](https://github.com/Java-Java-Bootcamp/booking/blob/main/imgs/booking-create-booking.png)
