### ISSUE TITLE
Реализовать в API бронирования выдачу бронирования окнами

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/booking#7]
GET /booking?text={text}&limit={limit}&offset={offset}
limit - кол-во записей в ответе
offset - на какое кол-во нужно сдвинуться

например, limit = 10 offset=20 означает, что в ответ API попадет 10 записей начиная с 21.

**Comment by slovpunk** [comment]
Напишу сюда, чтобы обратить внимание на занятии -- мне кажется мы зря мерджим сразу в main.
